main/urls.py
from django.urls import path,  include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.registerView, name='register'),
    path('login/', views.loginView, name='login'),
    path('upload/', views.uploadView, name='upload'),
    path('logout/', views.logoutView, name='logout'),
    path('folder/<int:pk>/', views.folderView, name='folder'),
    path('folder/add/', views.createFolder, name='add_folder'),
    #path('add/<int:pk>/<int:folder_id>/', views.addFile, name='add_file')
    path('add/<int:pk>/<str:id>/', views.addFile, name='add_file'),
    path('add/user/<int:pk>/', views.addUser, name='add_user'),
    path('search/', views.searchResults, name='results'),
    path('user/search/', views.searchUser, name='search'),
    path('file/<int:pk>/delete/', views.deleteFile, name='delete'),
]

sharely/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', include('main.urls')),
    path('login/', include('main.urls')),
    path('upload/', include('main.urls')),
    path('logout/', include('main.urls')),
    path('folder/<int:pk>/', include('main.urls')),
    path('folder/add/', include('main.urls')),
    #path('add/<int:pk>/<int:folder_id>/', include('main.urls')),
    path('add/<int:id>/<int:pk>/', include('main.urls')),
    path('add/user/<int:pk>/', include('main.urls')),
    path('search/', include('main.urls')),
    path('user/search/', include('main.urls')),
    path('file/<int:pk>/delete/', include('main.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User


class File(models.Model):
    file = models.FileField(upload_to='files/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Folder(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.ManyToManyField(File, related_name='files', blank=True)
    allowed_user = models.ManyToManyField(User, related_name='allowed_users', blank=True)

    def __str__(self):
        return self.name


class Link(models.Model):
    key = models.CharField(primary_key=True, max_length=50)
    folder = models.ForeignKey(Folder, unique=True, on_delete=models.CASCADE)


class Comment(models.Model):
    comment_folder = models.ForeignKey(Folder, related_name='comments', on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import File, Folder, Comment
from crispy_forms.helper import FormHelper


class FileForm(ModelForm):
    class Meta:
        model = File
        fields = ('title', 'file',)


class FolderForm(ModelForm):
    class Meta:
        model = Folder
        fields = ('name',)

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        ordering = ['date',]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.form_show_errors = False

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from .models import File, Folder
from .forms import FileForm, FolderForm, CommentForm
from django.http import HttpResponseRedirect

def homepage(request):
    if request.user.is_authenticated:
        files = File.objects.filter(user=request.user)
        folders = Folder.objects.filter(user=request.user)
        all_folders = Folder.objects.all()
        return render(request, 'main/homepage.html', {'files':files, 'folders':folders, 'all_folders':all_folders})
    else:
        return  render(request, 'main/homepage.html')


def registerView(request):
    form = UserCreationForm(request.POST)

    if form.is_valid():
        user = form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        login(request, user)
        return redirect('/')

    return render(request, 'main/register.html', {'form':form})


def loginView(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')
    return render(request, 'main/login.html',  {'form':form})


def logoutView(request):
    logout(request)
    return redirect('/')


def uploadView(request):
    form = FileForm(request.POST, request.FILES)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect('/')

    else:
        print(form.errors)

    return render(request, 'main/upload.html', {'form': form})


def deleteFile(request, pk):
    File.objects.filter(pk=pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def folderView(request, pk):
    all_folders = Folder.objects.all()
    folders =  Folder.objects.filter(pk=pk)
    form = CommentForm(request.POST)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.comment_user = request.user
        instance.comment_folder = get_object_or_404(Folder, pk=pk)
        instance.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, 'main/folder.html', {'folders':folders, 'all_folders':all_folders, 'form':form})


def createFolder(request):
    form = FolderForm(request.POST)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect('/')

    return render(request, 'main/add_folder.html', {'form':form})


def addUser(request, pk):
    if request.method == 'POST':
        searched = request.POST['searched']
        searched_user = User.objects.get(username=searched)
        folder = Folder.objects.get(pk=pk)
        #user = User.objects.get(username=searched_user)
        folder.allowed_user.add(searched_user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def addFile(request, pk, id):
    folder = Folder.objects.get(pk=id)
    new_file = File.objects.get(pk=pk)
    folder.file.add(new_file)
    return redirect('/')


def searchResults(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        user_list = User.objects.filter(username__contains=searched)
        return render(request, 'main/search_results.html', {'searched':searched, 'list':user_list})
    else:
        return render('/')


def searchUser(request):
    return render(request, 'main/search.html')

main/templates/main/add_folder.html
{% extends 'base.html' %}
{% block content %}
<div style="width:40%; margin: auto">
    <div class="card p-5 my-5">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <p>{{field.label_tag}}</p>
                    {{field}}
                {% endfor %}
                <br>
                <button class="btn btn-success my-4">add folder</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/folder.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %} 
<script src="{% static 'LoadComments.js' %}"></script>
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <br>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 me-md-auto align-items-center align-items-sm-start text-decoration-none text-white" id="menu">
                    <li class="nav-item px-2">
                        <div class="dropdown">
                            <a class="btn btn-primary dropdown-toggle px-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-plus fa-lg"></i>
                                <span>New</span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                              <li><a class="dropdown-item" href="{% url 'main:add_folder' %}">Folder</a></li>
                              <li><a class="dropdown-item" href="{% url 'main:upload' %}">Upload</a></li>
                            </ul>
                        </div>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a href="{% url 'main:homepage' %}" class="nav-link align-middle px-0 text-decoration-none text-white">
                            <i class="fa fa-home fa-lg px-2" witdh=15 height=15></i><span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <br>
                    <li class="nav-header">
                        <h5 class="px-2">My folders:</h5>
                    </li>
                    {% for folder in all_folders %}
                        {% if folder.user.pk == request.user.pk %}
                            <li class="nav-item">
                                <a href="{% url 'main:folder' folder.pk %}" class="nav-link align-middle px-0 text-decoration-none text-white">
                                    <i class="fa fa-folder-o fa-lg px-2"></i><span class="ms-1 d-none d-sm-inline" style="margin-left: 10%">{{folder.name}}</span>
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <br>
                    <li class="nav-header">
                        <h5 class="px-2">Shared with me:</h5>
                    </li>
                    {% for folder in all_folders %}
                        {% if request.user in folder.allowed_user.all %}
                            <li class="nav-item">
                                <a href="{% url 'main:folder' folder.pk %}" class="nav-link align-middle px-0 text-decoration-none text-white">
                                    <i class="fa fa-folder-o fa-lg px-2"></i><span class="ms-1 d-none d-sm-inline" style="margin-left: 10%">{{folder.name}}</span>
                                </a>
                            </li> 
                        {% endif %}
                    {% endfor %}
                </ul>
                <hr>
            </div>
        </div>
        <div class="col py-3">
            {% for folder in folders %}
                {% if request.user in folder.allowed_user.all or request.user == folder.user %}
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <h3>{{folder.name}}</h3>
                            <div class="btn-group" role="group">
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary mb-3 my-auto" data-bs-toggle="modal" data-bs-target="#exampleModal" aria-label="Basic">
                                    Invite contributor
                                </button>
                                <button onclick="loadComments()" class="btn btn-outline-primary mb-3 my-auto">Comments</button>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Add a contributor</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <form method="POST" action="{% url 'main:add_user' pk=folder.pk%}">
                                                    {% csrf_token %}
                                                    <input name="searched" class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> 
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                {% endif %}
            {% endfor %}
            <br>
            <!-- COMMENT SECTION -->
            <div id="comments" class="d-none">
                <div class="card shadow">
                    <div class="card-header">
                        Comments:
                    </div>
                    <form method="POST" class="px-3 py-2">
                        {% csrf_token %}
                        {% for field in form %}
                            {{field|as_crispy_field}}
                        {% endfor %}
                        <button class="btn btn-primary mt-4">Comment</button>
                    </form>
                    <div class="card-body">
                        {% for folder in folders %}
                            {% for comment in folder.comments.all %}
                                <div class="card shadow-sm">
                                    <div class="card-body">
                                        <div class="d-flex">
                                            <p class="small d-flex flex-grow-1" style="margin-bottom: -0.2%">{{comment.comment_user}}</p>
                                            <p class="small ml-auto flex-row-reverse">{{comment.date}}</p>
                                        </div>
                                        <hr style="margin-top: -0.2%; margin-bottom: -0.1%">
                                        <p class="card-text my-1">{{comment.content}}</p>
                                    </div>
                                </div>
                                <br>
                            {% endfor %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- END OF COMMENT SECTION -->
            <br>
            <ul class="list-group ">
                {% for folder in folders %}
                    {% for file in folder.file.all %}
                        {% if request.user in folder.allowed_user.all or request.user == folder.user %}
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto my-auto">
                                    <div class=""><a class="text-decoration-none" href="{{file.file.url}}">{{file.title}}</a></div>
                                </div>
                                <div class="btn-group">
                                    <a role="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    options 
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        <li><h6 class="dropdown-header">Add to:</h6></li>
                                        {% for folder in all_folders %}
                                            {% if request.user == folder.user %}
                                            <li><a class="dropdown-item" href="{% url 'main:add_file' pk=file.pk id=folder.id%}">{{folder.name}}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        <li><h6 class="dropdown-header">Shared folders:</h6></li>
                                        {% for folder in all_folders %}
                                            {% if request.user in folder.allowed_user.all%}
                                            <li><a class="dropdown-item" href="{% url 'main:add_file' pk=file.pk id=folder.id%}">{{folder.name}}</a></li> 
                                            {% endif %}
                                        {% endfor %}
                                        <li><h6 class="dropdown-header">Options</h6></li>
                                        <li><a class="dropdown-item text-danger" href="{% url 'main:delete' file.pk %}">Delete</a></li>
                                    </ul>
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
              </ul> 
        </div>
    </div>
</div>



{% endblock %}

main/templates/main/homepage.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
{% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <br>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 me-md-auto align-items-center align-items-sm-start text-decoration-none text-white" id="menu">
                        <li class="nav-item px-2">
                            <div class="dropdown">
                                <a class="btn btn-primary dropdown-toggle px-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-plus fa-lg"></i>
                                    <span>New</span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                  <li><a class="dropdown-item" href="{% url 'main:add_folder' %}">Folder</a></li>
                                  <li><a class="dropdown-item" href="{% url 'main:upload' %}">Upload</a></li>
                                </ul>
                            </div>
                        </li>
                        <br>
                        <li class="nav-item">
                            <a href="{% url 'main:homepage' %}" class="nav-link align-middle px-0 text-decoration-none text-white">
                                <i class="fa fa-home fa-lg px-2" witdh=15 height=15></i><span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        <br>
                        <li class="nav-header">
                            <h5 class="px-2">My folders:</h5>
                        </li>
                        {% for folder in folders %}
                            {% if folder.user.pk == request.user.pk %}
                                <li class="nav-item">
                                    <a href="{% url 'main:folder' folder.pk %}" class="nav-link align-middle px-0 text-decoration-none text-white">
                                        <i class="fa fa-folder-o fa-lg px-2"></i><span class="ms-1 d-none d-sm-inline" style="margin-left: 10%">{{folder.name}}</span>
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <br>
                        <li class="nav-header">
                            <h5 class="px-2">Shared with me:</h5>
                        </li>
                        {% for folder in all_folders %}
                                {% if request.user in folder.allowed_user.all %}
                                    <li class="nav-item">
                                        <a href="{% url 'main:folder' folder.pk %}" class="nav-link align-middle px-0 text-decoration-none text-white">
                                            <i class="fa fa-folder-o fa-lg px-2"></i><span class="ms-1 d-none d-sm-inline" style="margin-left: 10%">{{folder.name}}</span>
                                        </a> 
                                    </li>
                                {% endif %}
                        {% endfor %}
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="col py-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <h3>Home</h3>
                    </li>
                </ul>
                <ul class="list-group ">
                    {% for file in files %}
                        {% if file.user.pk == request.user.pk %}
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto my-auto">
                                <div class=""><a class="text-decoration-none" href="{{file.file.url}}">{{file.title}}</a></div>
                            </div>
                            <div class="btn-group">
                                <a role="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                options 
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li><h6 class="dropdown-header">Add to:</h6></li>
                                    {% for folder in folders %}
                                        <li><a class="dropdown-item" href="{% url 'main:add_file' pk=file.pk id=folder.id%}">{{folder.name}}</a></li>
                                    {% endfor %}
                                    <li><h6 class="dropdown-header">Shared folders:</h6></li>
                                    {% for folder in all_folders %}
                                        {% if request.user in folder.allowed_user.all %}
                                            <li><a class="dropdown-item" href="{% url 'main:add_file' pk=file.pk id=folder.id%}">{{folder.name}}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    <li><h6 class="dropdown-header">Options</h6></li>
                                    <li><a class="dropdown-item text-danger" href="{% url 'main:delete' file.pk %}">Delete</a></li>
                                </ul>
                            </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                  </ul> 
            </div>
        </div>
    </div>
{% else %}
    <div class="py-5 my-5"></div>
    <div class="my-5">
        <div class="container col-xxl-8 px-4 py-5 my-auto">
            <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                <div class="col-10 col-sm-8 col-lg-6 overflow-hidden">
                    <img src="{% static 'screenshot.png' %}" height=500 class="img-fluid rounded">
                </div>
                <div class="col-lg-6">
                    <h1 class="display-5 fw-bold lh-1 mb-3">Share.ly</h1>
                    <p class="lead">
                        Quickly share and manage projects with contributors using Sharely. The easiest management tool available, allowing you to quickly share folders and lead projects, as well as directly communicate with a project’s team members.
                    </p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a class="btn btn-primary btn-lg px-4 me-md-2">Sign up</a>
                        <a class="btn btn-outline-primary btn-lg px-4">Log in</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="my-5 py-5"></div>
    <div class="container px-4 pt-5" id="hanging-icons"> <h2 class="pb-2 border-bottom mx-1 text-primary">Features</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
          <div class="col d-flex align-items-start">
            <div>
              <h2 class="text-primary">File Management</h2>
              <p>Easy-to-use file sharing and management, allowing you to collaborate with others as well as maintain solo projects. </p>
            </div>
          </div>
          <div class="col d-flex align-items-start">
            <div>
              <h2 class="text-primary">Easy Collaboration</h2>
              <p>Add comments and remarks to all shared folders, making communication and version control easier and more intuitive than ever before. </p>
            </div>
          </div>
          <div class="col d-flex align-items-start">
            <div>
              <h2 class="text-primary">Intuitive UI</h2>
              <p>A simple and powerful interface allows users to take full advantage of Share.ly's features without being held back by clunky UI, and unoptimized features.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-10 col-lg-9 overflow-hidden mx-auto pt-5 mt-5">
        <img src="{% static 'screenshot4.png' %}" class="img-fluid rounded overflow-hidden mx-auto">
     </div>
{% endif %}
{% endblock %}

main/templates/main/login.html
{% extends 'base.html' %}

{% block content %}
<div style="width:40%; margin: auto">
    <div class="card p-5 my-5">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <p>{{field.label_tag}}</p>
                {{field}}
                <br>
            {% endfor %}
            <button class="btn btn-success my-4">Log in</button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/register.html
{% extends 'base.html' %}

{% block content %}
<div style="width:40%; margin: auto">
    <div class="card p-5 my-5">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <p>{{field.label_tag}}</p>
                {{field}}
            {% endfor %}
            <br>
            <button class="btn btn-success my-4">sign up</button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/search.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="{% url 'main:results' %}">
    {% csrf_token %}
    <input name="searched" class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> 
</form>
{% endblock %}

main/templates/main/search_results.html
{% extends 'base.html' %}

{% block content %}
    

<p>search page</p>
{% if searched %}
    <p>{{searched}}</p>
    {% for user in list %}
        <a href="#">{{user}}</a>
    {% endfor %}




{% else %}
    <p>woops</p>
{% endif %}


{% endblock %}

main/templates/main/upload.html
{% extends 'base.html' %}

{% block content %}
<div style="width:40%; margin: auto">
    <div class="card p-5 my-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <p>{{field.label_tag}}</p>
                {{field}}
            {% endfor %}
            <br>
            <button class="btn btn-success my-4">upload</button>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body style="height:100%">
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-1 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'main:homepage' %}">
           share.ly 
        </a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                {% if user.is_authenticated %}
                <a class="btn btn-danger px-3" href="{% url 'main:logout' %}">Sign out</a>
                {% else %}
                    <a class="btn btn-light" href="{% url 'main:login' %}">Log in</a>
                    <a class="btn btn-primary px-3" href="{% url 'main:register' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
    </header>
  
    {% block content %}
    {% endblock %}
</body>
</html>